export interface CategoryProps {
  category: string; // Fetch Param
  displayName: string;
  thumbnailURL?: string;
}
export interface TagProps {
  [x: string]: string;
  name: string;
  value: string;
}
export const categoryData = {
  brand: [
    {
      id: 0,
      name: '사진',
      displayName: '스튜디오',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=9',
      category: require('@images/category_img/cate_icon_studio.jpg'),
      tags: [
        '전체',
        '웨딩촬영',
        '본식스냅',
        '가봉스냅',
        '세미촬영',
        '데이트스냅',
        '허니문스냅',
        '토탈웨딩',
        '인물중심',
        '배경다양',
        '자연광',
        '야간씬',
        '한복씬',
        '흑백씬',
        '옥상씬',
        '파스텔톤',
        '심플한',
        '로드씬',
        '가든씬',
        '식물',
        '캐주얼씬',
        '발랄한',
        '모니터링촬영',
        '커스터마이징',
        '프라이빗',
        '반려동물',
        '연예인선호',
      ],
    },
    {
      id: 1,
      name: '드레스',
      displayName: '드레스',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=10',
      category: require('@images/category_img/cate_icon_dress.jpg'),
      tags: [
        '전체',
        '디자이너브랜드',
        '수입드레스',
        '세미드레스',
        '러블리',
        '심플한',
        '우아한',
        '유니크',
        '클래식',
        '화려한',
        '섹시한',
        '공주풍',
        '여신스타일',
        '청순한',
        '연예인선호',
      ],
    },
    {
      id: 2,
      name: '헤어',
      displayName: '헤어/메이크업',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=11',
      category: require('@images/category_img/cate_icon_hair.jpg'),
      tags: ['전체', '출장헤어메이크업', '포인트', '스모키', '내추럴', '컨투어링', '윤광', '동안', '연예인선호'],
    },
    {
      id: 3,
      name: '웨딩홀',
      displayName: '웨딩홀',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=16',
      category: require('@images/category_img/cate_icon_hall.jpg'),
    },
    {
      id: 4,
      name: '신혼여행',
      displayName: '신혼여행',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=35',
      category: require('@images/category_img/cate_icon_honeymoon.jpg'),
      tags: [
        '전체',
        '허니문스냅',
        '여행사',
        '관광',
        '휴양',
        '휴양+관광',
        '하와이',
        '몰디브',
        '발리',
        '칸쿤',
        '유럽',
        '코사무이',
        '미국',
        '호주',
        '괌',
        '사이판',
        '뉴질랜드',
        '푸켓',
        '베트남',
        '세이셸',
        '기타지역',
        '대형여행사',
        '전문여행사',
      ],
    },
    {
      id: 5,
      name: '한복',
      displayName: '한복',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=19',
      category: require('@images/category_img/cate_icon_hanbok.jpg'),
      tags: ['전체', '맞춤', '대여', '맞춤대여', '일반대여', '예단', '연예인선호', '드라마협찬', '파스텔톤', '진한톤', '트렌디', '전통미'],
    },
    {
      id: 6,
      name: '예복',
      displayName: '예복',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=18',
      category: require('@images/category_img/cate_icon_yebok.jpg'),
      tags: [
        '전체',
        '맞춤',
        '대여',
        '기성복',
        '남성예복',
        '여성예복',
        '커플턱시도',
        '대여턱시도',
        '세미드레스',
        '원피스',
        '투피스',
        '연예인선호',
        '클래식',
        '트렌디',
        '유니크',
        '대중적',
        '수제',
        '반수제',
        '프리미엄라인',
      ],
    },
    {
      id: 7,
      name: '예물',
      displayName: '예물',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=17',
      category: require('@images/category_img/cate_icon_yemul.png'),
      tags: ['전체', '반지', '시계', '심플한', '유니크', '클래식', '트렌디', '전국'],
    },
    {
      id: 8,
      name: '침구',
      displayName: '침구',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=61',
      category: require('@images/category_img/cate_icon_bed.jpg'),
      tags: [
        '전체',
        '예단침구',
        '신혼침구',
        '구스',
        '맞춤침구',
        '한실침구',
        '양실침구',
        '브랜드침구',
        '클래식',
        '트렌디',
        '반상기',
        '은수저',
      ],
    },
    {
      id: 9,
      name: '영상앨범',
      displayName: '본식 DVD',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=67',
      category: require('@images/category_img/cate_icon_dvd.jpg'),
      tags: [
        '전체',
        '리허설영상',
        '본식영상',
        '포토영상',
        '뮤직비디오형',
        '다큐멘터리형',
        '뮤직+다큐멘터리형',
        'USB',
        'DVD',
        '파일만',
        '전국',
      ],
    },
    {
      id: 10,
      name: '부케',
      displayName: '부케/꽃장식',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=60',
      category: require('@images/category_img/cate_icon_bouquet.jpg'),
    },
    {
      id: 11,
      name: '폐백',
      displayName: '폐백/이바지',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=49',
      category: require('@images/category_img/cate_icon_pyebaek.jpg'),
      tags: ['전체', '폐백', '이바지', '답례품'],
    },
    {
      id: 12,
      name: '웨딩카',
      displayName: '웨딩카',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=58',
      category: require('@images/category_img/cate_icon_car.jpg'),
      tags: ['전체', '웨딩카', '국산차', '수입차', '리무진'],
    },
    {
      id: 13,
      name: '연주',
      displayName: '웨딩연주',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=65',
      category: require('@images/category_img/cate_icon_inst.jpg'),
      tags: ['전체', '팝페라', '재즈', '뮤지컬', '성악', '피아노', '독창', '중창', '현악', '연주', '축가'],
    },
    {
      id: 14,
      name: '슈즈',
      displayName: '웨딩슈즈',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=59',
      category: require('@images/category_img/cate_icon_shoes.jpg'),
      tags: ['전체', '맞춤슈즈', '기성슈즈', '프러포즈슈즈', '레이스', '새틴', '소가죽', '실크', '벨벳'],
    },
    {
      id: 15,
      name: '사회자',
      displayName: '사회자',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=64',
      category: require('@images/category_img/cate_icon_mc.jpg'),
      tags: ['주례자', '주례없는사회자', '주례있는예식사회자'],
    },
    {
      id: 16,
      name: '케어',
      displayName: '스킨케어/마사지',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=62',
      category: require('@images/category_img/cate_icon_care.jpg'),
      tags: ['전체', '스킨케어', '바디케어', '아로마케어', '스파', '경락', '연예인선호', '전국'],
    },
    {
      id: 17,
      name: '청첩장',
      displayName: '청첩장',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=63',
      category: require('@images/category_img/cate_icon_invite.jpg'),
      tags: ['전체', '일반청첩장', '프리미엄청첩장', '모바일청첩장'],
    },
    {
      id: 18,
      name: '혼수',
      displayName: '혼수',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=70',
      category: require('@images/category_img/cate_icon_honsu.jpg'),
      tags: ['전체'],
    },
    {
      id: 19,
      name: '파티',
      displayName: '파티/이벤트',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=68',
      category: require('@images/category_img/cate_icon_event.jpg'),
    },
    {
      id: 20,
      name: '답례품',
      displayName: '답례품',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=66',
      category: require('@images/category_img/cate_icon_gift.jpg'),
      tags: ['전체', '떡', '도시락', '과일', '수제청', '한과'],
    },
  ],
  product: [
    {
      id: 0,
      name: '패키지',
      displayName: '패키지',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=9',
      category: require('@images/category_img/cate_icon_studio.jpg'),
      tags: ['전체', '스드메', '드메', '토탈+드메', '영상+스냅', '드메+스냅+영상'],
    },
    {
      id: 1,
      name: '사진',
      displayName: '사진',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=10',
      category: require('@images/category_img/cate_icon_dress.jpg'),
      tags: ['전체', '토탈촬영', '세미촬영', '본식스냅', '하이엔드'],
    },
    {
      id: 2,
      name: '드레스',
      displayName: '드레스',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=10',
      category: require('@images/category_img/cate_icon_dress.jpg'),
      tags: ['전체', '리허설+본식', '본식만', '리허설만', '수입드레스샵', '하이엔드', '토탈촬영'],
    },
    {
      id: 3,
      name: '헤어/메이크업',
      displayName: '헤어/메이크업',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=11',
      category: require('@images/category_img/cate_icon_hair.jpg'),
      tags: ['전체', '리허설+본식', '본식만', '리허설만', '여자혼주', '남자혼주'],
    },
    {
      id: 4,
      name: '예복',
      displayName: '예복',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=18',
      category: require('@images/category_img/cate_icon_yebok.jpg'),
      tags: ['전체', '맞춤예복', '대여예복', '국내원단', '수입원단', '영국원단', '이태리원단'],
    },
    {
      id: 5,
      name: '한복',
      displayName: '한복',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=19',
      category: require('@images/category_img/cate_icon_hanbok.jpg'),
      tags: ['전체', '맞춤한복', '대여한복', '혼주한복'],
    },
    {
      id: 6,
      name: '예물',
      displayName: '예물',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=17',
      category: require('@images/category_img/cate_icon_yemul.png'),
      tags: ['전체', '웨딩밴드', '100만원이하', '100~150만원', '150~200만원', '200만원이상'],
    },
    {
      id: 7,
      name: '영상앨범',
      displayName: '본식DVD',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=67',
      category: require('@images/category_img/cate_icon_dvd.jpg'),
      tags: ['전체', '본식영상', '리허설영상', '1인촬영', '2인촬영', '메이크업씬O', '메이크업씬X'],
    },
    {
      id: 8,
      name: '부케/꽃장식',
      displayName: '부케',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=60',
      category: require('@images/category_img/cate_icon_bouquet.jpg'),
      tags: ['전체', '핑크', '피치', '화이트', '레드', '블루', '옐로', '퍼플', '믹스', '장미', '카라', '튤립', '작약'],
    },
    {
      id: 9,
      name: '폐백',
      displayName: '폐백/이바지',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=49',
      category: require('@images/category_img/cate_icon_pyebaek.jpg'),
      tags: ['전체', '닭메인', '육포메인', '닭+육포', '실속형', '프리미엄형', '이바지단품', '이바지세트'],
    },
    {
      id: 10,
      name: '축하연주',
      displayName: '연주/사회자',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=65',
      category: require('@images/category_img/cate_icon_inst.jpg'),
      tags: ['전체', '피아노', '현악', '재즈', '뮤지컬', '축가', '사회자'],
    },

    {
      id: 11,
      name: '웨딩카',
      displayName: '웨딩카',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=58',
      category: require('@images/category_img/cate_icon_car.jpg'),
    },
    {
      id: 12,
      name: '답례품',
      displayName: '답례품',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=66',
      category: require('@images/category_img/cate_icon_gift.jpg'),
    },

    {
      id: 13,
      name: '웨딩슈즈',
      displayName: '웨딩슈즈',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=59',
      category: require('@images/category_img/cate_icon_shoes.jpg'),
    },
    {
      id: 14,
      name: '청첩장',
      displayName: '청첩장',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=63',
      category: require('@images/category_img/cate_icon_invite.jpg'),
    },

    {
      id: 15,
      name: '파티/이벤트',
      displayName: '프러포즈',
      url: 'https://www.iwedding.co.kr/brand/main?sectors_depth1_no=35',
      category: require('@images/category_img/cate_icon_honeymoon.jpg'),
      tags: ['전체', '공개프러포즈', '비공개프러포즈', '레스토랑', '요트', '신혼집', '갤러리', '소극장'],
    },
  ],
};
